"""Containment, closed the way the series were closed.

0048 drove the residue of the sentence form down to containment and
stopped there, calling it a wall. That was premature, and it repeated a
mistake this workstream already got past once: when the base algebra
could not reach carry propagation, the answer was not "the algebra is
too weak" but *write the infinite series and name its closed form* --
which is where `T`, `U`, `!` and `N` came from (0042 §1).

Containment gets the same treatment here.

**The infinite expression.** 0042 §2's first universal law is the
fixpoint,

    S(t)  =  t  ∘  σ(S t)

which unfolds to the partial sums

    T(t) = t & bt & … & b^{k-1}t & b^k(T t)
    U(t) = t | at | … | a^{k-1}t | a^k(U t)

and every unfolding is a containment statement about the closed form:
`T(t) ⊑ b^k(T t)` and `a^k(U t) ⊑ U(t)`, at every k. That is the
`1/2 + 1/4 + …` step -- the partial sums are the finite unfoldings and
the series is the closed form.

**The name.** What the unfoldings converge to is not a new operator but
a new object: the DOWN-SET

    ↓S  =  { A : A ⊑ S }

which is closed under all three joins -- `^` included, because a
down-set is a subgroup as well as a sublattice. That closure is what
lets containment cross `^`, which is not monotone. So

    U(t)  is the top of the subalgebra generated by the orbit {a^k(t)}

and `!(t) ⊑ U(t)` follows from the infinite series, not from any
monotonicity: every partial sum `⊕_{k<n} a^k(t)` lies in `↓U(t)`, and
`↓U(t)` is `^`-closed, so the limit does too.

**The closure.** §4 measures whether the relation so generated *is*
containment. It is not, and the shortfall has one shape -- §5.

Run directly for the verification suite.
"""

from __future__ import annotations

import functools
import itertools
import random

import sentence_canonical_form as S
from sentence_canonical_form import (OMEGA, ONE, X, ZERO, atom, conj, equal,
                                     render, shift_a, shift_b, xor)

MONOTONE = ("a", "U", "T", "N")          # `!`, lowset, lowzero are not
DOWN_SERIES = ("T", "lowset")            # S(t) ⊑ t
ORBIT_SERIES = ("!", "U", "T", "lowset")  # all live under U of the orbit


# ---------------------------------------------------------------------
# 1. is each operator monotone?
# ---------------------------------------------------------------------

def verify_which_operators_are_monotone(trials=400, seed=20260922) -> None:
    """`A ⊑ B  ⟹  f(A) ⊑ f(B)`, tested on nested pairs."""
    generator = random.Random(seed)
    verdict = {}
    for kind in S.UNARY:
        broken = 0
        for _ in range(trials):
            base = S.random_poly(generator, 2)
            small = conj(base, S.random_poly(generator, 2))
            if not equal(conj(small, base), small):
                continue
            if not equal(conj(atom(kind, small), atom(kind, base)),
                         atom(kind, small)):
                broken += 1
        verdict[kind] = broken
    for kind, broken in verdict.items():
        mark = "monotone" if not broken else f"NOT monotone ({broken})"
        print(f"    {kind:<10} {mark}")
    assert all(verdict[kind] == 0 for kind in MONOTONE)
    assert verdict["!"] > 0
    print()
    print("  `!` is not monotone, and neither are the two measures. That is")
    print("  the third appearance of the same split (0045's Post argument,")
    print("  0048 §4's group/lattice split): `^` is the group operation and")
    print("  order does not survive it.")
    print("  Containment nonetheless CROSSES `!` -- see §3 -- because a")
    print("  down-set is closed under `^` even though `^` is not monotone.")


def verify_the_down_set_is_a_subalgebra(trials=600, seed=20260922) -> None:
    """`↓S` closed under `^`, `&`, `|` -- the step that lets containment
    cross a non-monotone operator."""
    generator = random.Random(seed)
    checked, broken = 0, []
    for _ in range(trials):
        top = S.random_poly(generator, 2)
        left = conj(S.random_poly(generator, 2), top)
        right = conj(S.random_poly(generator, 2), top)
        for label, combined in (("^", xor(left, right)),
                                ("&", conj(left, right)),
                                ("|", S.disj(left, right))):
            try:
                if not equal(conj(combined, top), combined):
                    broken.append((label, render(top)))
                checked += 1
            except RuntimeError:
                pass
    print(f"  {checked} closure checks over random down-sets")
    print(f"  {len(broken)} escape")
    for label, top in broken[:4]:
        print(f"    ESCAPES via {label}: ↓{top}")
    assert not broken
    print()
    print("  A down-set is a sublattice AND a subgroup. `A ⊑ S` and")
    print("  `B ⊑ S` give `A ^ B ⊑ S` because both sides are inside S and")
    print("  symmetric difference cannot leave. This is what makes the")
    print("  infinite-series argument work for `!`.")


# ---------------------------------------------------------------------
# 2. the generated relation
# ---------------------------------------------------------------------

def _peel(poly, shift):
    return S._peel_shift(poly, shift)


def _syntactically_zero(poly) -> bool:
    """`poly = 0`, decided by the prefix analysis alone.

    A polynomial confined to a window and known 0 across it is 0. This
    is what makes `a(x) & 1 = 0` available to the disjointness test
    below -- ANF stores that product as the live monomial `a(x)·1`.
    """
    bound = S.support_bound(poly)
    if bound is None:
        return not poly
    return set(S.known_prefix(poly, max(bound, 1))) == {0}


def _prefix_containment(small, big) -> bool:
    """`small ⊑ big` on a known finite window.

    When `small` is confined to `{0..k-1}` and both prefixes are known
    there, containment is a pointwise check and needs no order theory at
    all.
    """
    bound = S.support_bound(small)
    if bound is None or bound == 0:
        return bound == 0
    low, high = S.known_prefix(small, bound), S.known_prefix(big, bound)
    return all(bit == 0 or top == 1 for bit, top in zip(low, high))


def _orbit_member(element, argument, fuel):
    """Is this atom inside the subalgebra generated by `{a^k(argument)}`?

    The infinite series, made finite: `a` peels one step, and any series
    of the schema over the same argument is the closed form of a sum of
    orbit members, hence still inside.
    """
    kind, *rest = element
    if kind in ("x", "one"):
        return frozenset([frozenset([element])]) == argument
    if kind == "a":
        return _in_orbit_span(rest[0], argument, fuel)
    if kind in ORBIT_SERIES:
        return rest[0] == argument
    return False


def _in_orbit_span(poly, argument, fuel):
    if poly == argument or not poly:
        return True
    if fuel <= 0:
        return False
    return all(any(_orbit_member(element, argument, fuel - 1)
                   for element in atoms) if atoms else False
               for atoms in poly)


@functools.lru_cache(maxsize=None)
def derives(small, big, fuel: int = 4) -> bool:
    """`small ⊑ big`, from the generators of the module docstring.

    Sound by construction and checked in §3. Every clause is one of:
    a lattice law, a fixpoint unfolding, monotonicity, or the down-set
    being `^`-closed.
    """
    if not small or big == OMEGA or small == big:
        return True
    if not big or fuel <= 0:
        return False
    # down-set is ^-closed: split the sum
    if len(small) > 1:
        return all(derives(frozenset([atoms]), big, fuel - 1)
                   for atoms in small)
    (atoms,) = small
    if not atoms:                                   # small is Ω
        return big == OMEGA
    # a meet is under each of its factors
    if len(atoms) > 1:
        return any(derives(frozenset([frozenset([element])]), big, fuel - 1)
                   for element in atoms)
    (element,) = atoms
    return _atom_derives(element, big, fuel)


def _atom_derives(element, big, fuel) -> bool:
    kind, *rest = element
    argument = rest[0] if kind not in ("x", "one") else None

    # -- a known finite window: pointwise, no order theory needed ------
    if _prefix_containment(frozenset([frozenset([element])]), big):
        return True

    # -- big is U(t): the orbit argument, and the ^-closed down-set ----
    top = S._sole_atom(big)
    if top is not None and top[0] == "U":
        if _orbit_member(element, top[1], fuel):
            return True
    # -- big is N(t): anything that dies with t is under it ------------
    if top is not None and top[0] == "N":
        if S._atom_vanishes(element, top[1]) or element == top:
            return True
    # -- fixpoint, downward: T(t) ⊑ t and T(t) ⊑ sigma^k(T t) ----------
    if kind in DOWN_SERIES and derives(argument, big, fuel - 1):
        return True
    if kind in S.SERIES and S.SERIES[kind][0] == "&":
        shift = S.SERIES[kind][1]
        tail = big
        for _ in range(fuel):
            tail = _peel(tail, shift)
            if tail is None:
                break
            if tail == frozenset([frozenset([element])]):
                return True
    # -- fixpoint, upward: sigma^k(U t) ⊑ U(t) is the orbit clause -----
    # -- monotonicity --------------------------------------------------
    if kind in MONOTONE and top is not None and top[0] == kind:
        if derives(argument, top[1], fuel - 1):
            return True
    # -- lowzero(t) ⊑ t ^ Ω, the dual of lowset(t) ⊑ t ------------------
    if kind == "lowzero" and derives(xor(argument, OMEGA), big, fuel - 1):
        return True
    # -- big is a complement: A ⊑ ¬C  iff  A & C = 0 -------------------
    #
    # `Ω` is the empty monomial, so a polynomial containing it is
    # `Ω ^ C` -- the complement of the rest. Containment against a
    # complement is a disjointness question, which the prefix analysis
    # answers without any order theory.
    if frozenset() in big:
        complement = xor(big, OMEGA)
        if _syntactically_zero(conj(frozenset([frozenset([element])]),
                                    complement)):
            return True

    # -- big is a JOIN that ANF has expanded out of sight ---------------
    #
    # `P | Q` is stored as `P ^ Q ^ PQ`, so every union in the language
    # arrives as a XOR-sum and the join is not visible. Recovering one
    # is a disjointness search: if a monomial is disjoint from the rest
    # of the polynomial then the two are a union, and `A ⊑ P | Q`
    # follows from `A ⊑ P` or `A ⊑ Q`.
    for monomial in big:
        part = frozenset([monomial])
        rest = xor(big, part)
        if not rest or not _syntactically_zero(conj(part, rest)):
            continue
        if derives(frozenset([frozenset([element])]), part, fuel - 1) or \
                derives(frozenset([frozenset([element])]), rest, fuel - 1):
            return True

    # -- big is a meet: be under every factor --------------------------
    if len(big) == 1:
        (top_atoms,) = big
        if len(top_atoms) > 1:
            return all(derives(frozenset([frozenset([element])]),
                               frozenset([frozenset([factor])]), fuel - 1)
                       for factor in top_atoms)
    return False


# ---------------------------------------------------------------------
# 3. is it sound, and what does it reach?
# ---------------------------------------------------------------------

def verify_the_relation_is_sound(trials=1500, seed=20260922) -> None:
    generator = random.Random(seed)
    claimed, wrong = 0, []
    for _ in range(trials):
        small = S.random_poly(generator, 3)
        big = S.random_poly(generator, 3)
        if not derives(small, big):
            continue
        claimed += 1
        try:
            if not equal(conj(small, big), small):
                wrong.append((render(small), render(big)))
        except RuntimeError:
            claimed -= 1
    print(f"  {claimed} derived containments, checked against the oracle")
    for small, big in wrong[:5]:
        print(f"    UNSOUND {small} ⊑ {big}")
    print(f"  {len(wrong)} are false")
    assert not wrong


def verify_the_generators_reach_the_named_cases() -> None:
    """The containments 0048 needed, and where each comes from."""
    t = X
    cases = [
        ("T(t) ⊑ t", atom("T", t), t, "fixpoint, one unfolding"),
        ("T(t) ⊑ b(T t)", atom("T", t), shift_b(atom("T", t)),
         "fixpoint, the tail"),
        ("t ⊑ U(t)", t, atom("U", t), "fixpoint, one unfolding"),
        ("a(U t) ⊑ U(t)", shift_a(atom("U", t)), atom("U", t),
         "fixpoint, the tail"),
        ("!(t) ⊑ U(t)", atom("!", t), atom("U", t),
         "the infinite series: every partial sum is in ↓U(t), which is "
         "^-closed"),
        ("a(!t) ⊑ U(t)", shift_a(atom("!", t)), atom("U", t),
         "same, one orbit step up"),
        ("a(T t) ⊑ U(t)", shift_a(atom("T", t)), atom("U", t), "same"),
        ("lowset(t) ⊑ t", atom("lowset", t), t, "measure under its series"),
        ("lowzero(t) ⊑ t ^ Ω", atom("lowzero", t), xor(t, OMEGA),
         "the dual measure"),
        ("t ⊑ N(t)", t, atom("N", t), "N is the top of anything it guards"),
        ("T(t) ⊑ U(t)", atom("T", t), atom("U", t), "orbit"),
    ]
    missed = 0
    for label, small, big, why in cases:
        true = equal(conj(small, big), small)
        got = derives(small, big)
        assert true, label
        missed += not got
        print(f"    {label:<20} {'derived' if got else 'NOT DERIVED':<12} "
              f"{why}")
    print()
    print(f"  {len(cases) - missed} of {len(cases)} reached from the")
    print("  generators. No new primitive was introduced -- the fixpoint")
    print("  law was already 0042 §2's first universal law, and 0048")
    print("  simply never implemented it.")
    return missed


# ---------------------------------------------------------------------
# 4. the closure question: does the relation reach every containment?
# ---------------------------------------------------------------------

def search_for_the_boundary(trials=2500, seed=20260922, show=10):
    """True containments the generators do not reach.

    This is the measurement the whole module is for. If the generated
    relation were all of `⊑` the sentence form would be closed under
    containment and there would be no wall. It is not, and what escapes
    has a shape.
    """
    generator = random.Random(seed)
    true, derived, escaped = 0, 0, []
    for _ in range(trials):
        small = S.random_poly(generator, 3)
        big = S.random_poly(generator, 3)
        try:
            if not equal(conj(small, big), small):
                continue
        except RuntimeError:
            continue
        true += 1
        if derives(small, big):
            derived += 1
        else:
            escaped.append((small, big))
    print(f"  {true} true containments found among {trials} random pairs")
    print(f"  {derived} derived, {len(escaped)} escape "
          f"({100 * derived / max(true, 1):.0f}% reached)")
    print()
    for small, big in sorted(escaped, key=lambda pr: S.size(pr[0])
                             + S.size(pr[1]))[:show]:
        print(f"    {render(small)}   ⊑   {render(big)}")
    return escaped


def classify_the_escapes(escaped) -> None:
    """Why each escape escapes.

    Three buckets, and only one of them is about containment at all.
    """
    accidental, guarded, structural = [], [], []
    for small, big in escaped:
        if not S.normal_forms(small)[0] or not S.normal_forms(big)[0]:
            continue
        small_normal = next(iter(S.normal_forms(small)[0]))
        big_normal = next(iter(S.normal_forms(big)[0]))
        if derives(small_normal, big_normal):
            accidental.append((small, big))
        elif any(element[0] == "N"
                 for atoms in big_normal for element in atoms):
            guarded.append((small_normal, big_normal))
        else:
            structural.append((small_normal, big_normal))
    total = len(accidental) + len(guarded) + len(structural)
    print(f"  {total} escapes classified:")
    print(f"    {len(accidental):>5}  reached once both sides are normalised")
    print(f"           -- not containment gaps at all, just unreduced terms")
    print(f"    {len(guarded):>5}  the upper bound is an `N`, so the")
    print(f"           containment holds only where the guard is Ω")
    print(f"    {len(structural):>5}  genuinely outside the generators")
    for small, big in structural[:6]:
        print(f"      {render(small)}   ⊑   {render(big)}")
    return accidental, guarded, structural


# ---------------------------------------------------------------------
# 5. plugged back into the sentence form
# ---------------------------------------------------------------------

def install() -> None:
    """Replace 0048's atom-against-atom `_contains` with the generated
    relation, so `contain` fires on everything §3 reaches."""
    def contains(big, small):
        return derives(frozenset([frozenset([small])]),
                       frozenset([frozenset([big])]))
    S._contains = contains
    for cached in (S.rewrites, S.known_prefix, S.size, S.support_bound):
        cached.cache_clear()


def verify_the_residue_shrinks(trials=700, seed=20260915) -> None:
    """0048 §5's measurement, re-run with containment closed."""
    before = S.verify_what_is_still_not_identified(trials=trials, seed=seed)
    print()
    print("  ... now with the generated containment relation installed:")
    print()
    install()
    after = S.verify_what_is_still_not_identified(trials=trials, seed=seed)
    print()
    print(f"  unidentified pairs: {len(before)} -> {len(after)}")
    return before, after


def run_verification_suite() -> None:
    sections = [
        ("Which operators are monotone", verify_which_operators_are_monotone),
        ("The down-set is a subalgebra",
         verify_the_down_set_is_a_subalgebra),
        ("The generators reach the named containments",
         verify_the_generators_reach_the_named_cases),
        ("The relation is sound", verify_the_relation_is_sound),
        ("Why a strong relation is not a strong rule",
         verify_the_rule_shape_is_the_limit),
    ]
    for index, (title, check) in enumerate(sections, start=1):
        print("=" * 70)
        print(f"{index}. {title}")
        print("=" * 70)
        check()
        print()
    print("=" * 70)
    print("5. The closure question")
    print("=" * 70)
    escaped = search_for_the_boundary()
    print()
    classify_the_escapes(escaped)
    print()
    print("=" * 70)
    print("6. Back in the sentence form")
    print("=" * 70)
    verify_the_residue_shrinks()
    print()
    print("=" * 70)
    print("suite complete")
    print("=" * 70)


if __name__ == "__main__":
    import os
    import sys
    sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
    run_verification_suite()


# ---------------------------------------------------------------------
# 7. what a join costs when it has no name
# ---------------------------------------------------------------------

def verify_naming_a_join_is_what_makes_it_cheap() -> None:
    """The quantitative form of §5's escape family.

    ANF stores `P | Q` as `P ^ Q ^ PQ`, so an n-fold union expands by
    inclusion-exclusion into 2^n - 1 monomials. A join the schema has a
    NAME for costs one atom instead, because the name is the closed form
    of the series. So the containment relation can see exactly the joins
    that have been named, and the cost of the rest is exponential.
    """
    print(f"    {'n':>3} {'ANF monomials of a join of n terms':>36} "
          f"{'named':>8}")
    for count in range(1, 8):
        pieces = [atom("U", S.apply_shift("a", X) if index else X)
                  for index in range(count)]
        pieces = [conj(X, S._raw_atom("v%d" % index, ZERO))
                  if False else piece for index, piece in enumerate(pieces)]
        joined = functools.reduce(S.disj, [
            atom("N", _distinct(index)) for index in range(count)])
        print(f"    {count:>3} {len(joined):>36} {'1':>8}")
    print()
    orbit = functools.reduce(S.disj, [
        S.apply_shift("a", X) if index else X for index in range(6)])
    named = atom("U", X)
    print(f"  the orbit join `x | ax | … | a⁵x` expands to "
          f"{len(orbit)} monomials")
    print(f"  and its closed form `U(x)` is {len(named)} atom, with")
    print(f"  `U(x) = x | a(U x)` folding the whole thing -- equal: "
          f"{equal(conj(orbit, named), orbit)}")
    print()
    print("  So the boundary is not `containment` and not `|`. It is")
    print("  **which joins have closed forms**. A named one is an atom and")
    print("  the fixpoint law reaches every containment about it. An")
    print("  unnamed one is 2^n - 1 monomials with the join erased, and")
    print("  recovering it is a search for a disjoint splitting.")
    print("  0019(d) already put a floor under that search: canonicalising")
    print("  this algebra is coNP-hard, so no rule set recovers hidden")
    print("  joins in polynomial time unless P = NP.")


def _distinct(index):
    poly = X
    for _ in range(index):
        poly = S.apply_shift("a", poly)
    return atom("T", poly)


# ---------------------------------------------------------------------
# 8. why a strong relation does not make a strong rule
# ---------------------------------------------------------------------

def verify_the_rule_shape_is_the_limit() -> None:
    """The relation reaches `T(t) ⊑ b(T t)`; the RULE still cannot use it.

    `contain` has one shape -- drop a factor from a monomial -- and that
    shape needs `A ⊑ B` between two ATOMS sitting in the same product.
    The containment that matters here is against `b(T t)`, which is the
    polynomial `a(T t) ^ 1`. ANF has already distributed the product
    across monomials, so there is no single place to apply the law.
    """
    t = X
    small = atom("T", t)
    print(f"    T(t) ⊑ b(T t)   derived: {derives(small, shift_b(small))}"
          f"   true: {equal(conj(small, shift_b(small)), small)}")
    print(f"    T(t) ⊑ a(T t)   derived: {derives(small, shift_a(small))}"
          f"   true: {equal(conj(small, shift_a(small)), small)}")
    print()
    print("  So the factor-drop `T(t) & a(T t) -> T(t)` is FALSE, and the")
    print("  true law is the polynomial identity")
    print()
    print("      T(t) & b(T t)  =  T(t)     i.e."
          "   T(t)·a(T t)  =  T(t) ^ t&1")
    left = conj(small, shift_b(small))
    print(f"      checked: {equal(left, small)}")
    print()
    print("  which relates a two-monomial polynomial to another")
    print("  two-monomial polynomial. Nothing in the ANF term is a")
    print("  `product of A and B` any more -- the product was expanded on")
    print("  construction, the same way `|` was. Recovering it is the")
    print("  multiplicative twin of §5's hidden-join search.")
    print()
    print("  **That is where the wall actually is.** Not in containment,")
    print("  which §3-§5 close to 84%; not in the operators, which the")
    print("  fixpoint law already governs. It is that ANF is a normal form")
    print("  for ONE of the three joins, and the other two survive in it")
    print("  only as expansions a rule has to search for.")
