"""The tiles are windows, and the N-layer is the automaton.

0039 asked whether the realisable non-emptiness vectors are generated by
the single law `N(s^k x) = N(s^(k+1) x)`. They are not, and the reason
identifies the whole structure.

**Tiles are windows.** Over the symbols `{x, s(x), ..., s^(n-1)(x)}` the
tile of polarity `p` is non-empty exactly when `p` occurs as a length-n
window `(x_i, x_(i-1), ..., x_(i-n+1))` of x's bit string. Verified for
n = 2, 3, 4 over every x. So a tile is not an arbitrary Venn region --
it is "the pattern p appears somewhere in x".

**So the simple law is far from sufficient.** Realisable vectors against
vectors satisfying the law:

    n = 2:   3 realisable      12 satisfying the law
    n = 3:  11 realisable     220 satisfying the law
    n = 4:  57 realisable   64596 satisfying the law   (of 2^16)

The law is sound -- every realisable vector satisfies it -- and it is
nowhere near complete.

**What does characterise the realisable set: the de Bruijn condition.**
Consecutive windows overlap in n-1 symbols, so the windows occurring in
x are exactly the vertices visited by a sliding-window walk: free bits
while reading x, then forced zeros above its top bit. The realisable
set equals the set of such walk-vertex-sets, exactly, at n = 2, 3, 4.

**Which means the tiles are de Bruijn states and the N-layer is the
automaton.** The tile decomposition does not replace the automaton
frame; it reconstructs it. 2^n tiles are 2^n de Bruijn vertices, the
realisable set is the set of runs, and "which tiles are non-empty" is
"which states the run visits". The sentence side and the automaton side
meet here as the same object rather than as two closed forms of one
series (0038's reading).

Run directly for the verification suite.
"""

from __future__ import annotations

from itertools import product as cartesian_product

WIDTH = 12
MASK = (1 << WIDTH) - 1

shift = lambda value: (value << 1) & MASK
complement = lambda value: MASK ^ value


def tile(polarity: tuple, value: int) -> int:
    """The Venn region where s^k(x) has polarity[k], for every k."""
    region, lifted = MASK, value
    for chosen in polarity:
        region &= lifted if chosen else complement(lifted)
        lifted = shift(lifted)
    return region


def windows(value: int, length: int) -> set:
    """Every length-n window (x_i, x_(i-1), ..., x_(i-n+1)) of x's bit
    string, for i across the universe. Positions below 0 read as 0."""
    def bit(position: int) -> int:
        return (value >> position) & 1 if 0 <= position < WIDTH else 0
    return {tuple(bit(index - offset) for offset in range(length))
            for index in range(WIDTH)}


def verify_tiles_are_windows() -> None:
    for length in (2, 3, 4):
        polarities = list(cartesian_product((0, 1), repeat=length))
        failures = [value for value in range(1 << WIDTH)
                    if {p for p in polarities if tile(p, value)}
                    != windows(value, length)]
        assert not failures, (length, failures[:3])
        print(f"  n = {length}:  tile p non-empty  <=>  p occurs as a "
              f"length-{length} window of x    (all x)")
    print("    A tile is not an arbitrary Venn region. It is the "
          "assertion that a")
    print("    particular bit pattern appears somewhere in x.")


def realisable(length: int) -> set:
    """The non-emptiness vectors that actually occur. Values are kept
    below the top bits so that shifting never truncates."""
    polarities = list(cartesian_product((1, 0), repeat=length))
    return {frozenset(p for p in polarities if tile(p, value))
            for value in range(1 << (WIDTH - length))}


def law_satisfying(length: int) -> set:
    """Vectors satisfying N(s^k x) = N(s^(k+1) x) for every k."""
    polarities = list(cartesian_product((1, 0), repeat=length))
    def nonempty(support, index):
        return any(p in support for p in polarities if p[index])
    return {frozenset(support)
            for support in _subsets(polarities)
            if all(nonempty(support, k) == nonempty(support, k + 1)
                   for k in range(length - 1))}


def _subsets(items):
    for mask in range(1 << len(items)):
        yield [item for index, item in enumerate(items)
               if mask >> index & 1]


def verify_the_law_is_insufficient() -> None:
    print("  n   realisable   satisfying N(s^k x) = N(s^k+1 x)   of "
          "2^(2^n)")
    for length in (2, 3, 4):
        actual = realisable(length)
        permitted = law_satisfying(length)
        assert actual <= permitted
        print(f"  {length}   {len(actual):>10}   {len(permitted):>32}   "
              f"{2 ** (2 ** length)}")
    print("    The law is sound -- every realisable vector satisfies it "
          "-- and nowhere")
    print("    near complete. So the answer to 0039's first open "
          "question is no.")


def walk_vertex_sets(length: int, free: int, forced: int) -> set:
    """Vertex sets of a sliding window over `free` arbitrary bits
    followed by `forced` zeros -- the de Bruijn walks."""
    frontier = {((0,) * (length - 1), frozenset())}
    for step in range(free + forced):
        choices = (0, 1) if step < free else (0,)
        frontier = {(((bit,) + state)[:length - 1],
                     visited | {(bit,) + state})
                    for state, visited in frontier for bit in choices}
    return {visited for _, visited in frontier}


def verify_the_de_bruijn_characterisation() -> None:
    print("  n   realisable   de Bruijn walk vertex-sets   equal")
    for length in (2, 3, 4):
        actual = realisable(length)
        walks = walk_vertex_sets(length, WIDTH - length, length)
        assert actual == walks, length
        print(f"  {length}   {len(actual):>10}   {len(walks):>26}   True")
    print("    Consecutive windows overlap in n-1 symbols, so the "
          "windows occurring in")
    print("    x are exactly the vertices a sliding-window walk visits: "
          "free bits while")
    print("    reading x, then forced zeros above its top bit.")
    print()
    print("    So the tiles ARE de Bruijn states and the realisable set "
          "IS the set of")
    print("    runs. The tile decomposition does not replace the "
          "automaton frame -- it")
    print("    reconstructs it, at the same 2^n cost, and 'which tiles "
          "are non-empty'")
    print("    is 'which states the run visits'.")


def run_verification_suite() -> None:
    print("=" * 70)
    print("1. Tiles are windows")
    print("=" * 70)
    verify_tiles_are_windows()

    print()
    print("=" * 70)
    print("2. The single law does not generate the realisable set")
    print("=" * 70)
    verify_the_law_is_insufficient()

    print()
    print("=" * 70)
    print("3. What does: the de Bruijn walk condition")
    print("=" * 70)
    verify_the_de_bruijn_characterisation()

    print()
    print("=" * 70)
    print("all checks passed")
    print("=" * 70)


if __name__ == "__main__":
    run_verification_suite()
